name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-lint-staged:
    name: Run lint-staged
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Install Node.js dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint "src/**/*.{ts,tsx,json}"
